# Generated by Django 2.2.6 on 2019-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
